# Test playbook to test PDB creation and cloaning
---
- hosts: oci-dbcs-ansible
  user: oracle
  become: yes
  become_user: oracle
  gather_facts: false 
  vars:
      service_name: orclcdb
      oracle_home: /opt/oracle/product/18c/dbhome_1
      source_pdb: orclpdb1
      new_pdb: orclpdb_test
      host: oci-dbcs-ansible
      pwd: WelCome123##
      pwd_usr: WelCome123##
      adm_user: sys
      mode: sysdba
      nu: pdb_admin_test
      clone_pdb: pdbclone
      cpu_count: 1
      storage: 2
  environment:
            ORACLE_HOME: /opt/oracle/product/18c/dbhome_1
            LD_LIBRARY_PATH: /opt/oracle/product/18c/dbhome_1/lib
  tasks:
    - name: Check pluggable database status
      oracle_pdb: 
        name: "{{ source_pdb }}"
        host: "{{ host }}"
        sourcedb: "{{ service_name }}"
        user: "{{ adm_user }}"
        mode: "{{ mode }}"
        password: "{{ pwd }}"
        state: status
        oracle_home: "{{ oracle_home }}"
    - name: Create new pluggable database
      oracle_pdb: 
        name: "{{ new_pdb }}"
        host: "{{ host }}"
        cpu_count: "{{ cpu_count }}"
        sourcedb: "{{ service_name }}"
        user: "{{ adm_user }}"
        mode: "{{ mode }}"
        password: "{{ pwd }}"
        dfd: /opt/oracle/oradata/ORCLCDB
        state: present
        storage: "{{ storage }}"
        oracle_home: "{{ oracle_home }}"
    - name: Check pluggable database status
      oracle_pdb: 
        name: "{{ new_pdb }}"
        host: "{{ host }}"
        sourcedb: "{{ service_name }}"
        user: "{{ adm_user }}"
        mode: "{{ mode }}"
        password: "{{ pwd }}"
        state: status
        oracle_home: "{{ oracle_home }}"
    - name: Create clone pluggable database
      oracle_pdb_clone:
        state: present
        host: "{{ host }}"
        user: "{{ adm_user }}"
        password: "{{ pwd }}"
        mode: "{{ mode }}"
        from_pdb: "{{ source_pdb }}"
        pdb_name: "{{ clone_pdb }}" 
        cdb: "{{ service_name }}"
        newuser: "{{ nu }}"
        newuser_password: "{{ pwd_usr }}"
        grants: 
         - dba  
    - name: Check pluggable database status
      oracle_pdb: 
        name: "{{ clone_pdb }}" 
        host: "{{ host }}"
        sourcedb: "{{ service_name }}"
        user: "{{ adm_user }}"
        mode: "{{ mode }}"
        password: "{{ pwd }}"
        state: status
        oracle_home: "{{ oracle_home }}" 
        
 